### PR TITLE
show an easy way to disable the hashtag list

### PR DESCRIPTION
**Pull request by anarcat**
it is not clear to me why the several_words_hashtags_list element is
present, what it does or why it is necessary. it also happens that
feed2tweet just works fine without it, so show a way to simply disable
that feature, by using /dev/null in the config directly

### CODE REVIEW

**Comment by chaica** [comment]
Hi,

Thanks for your PR, I'll read it asap and let you know what I think about it.

Cheers,
Carl

**Comment by chaica** [comment]
Hi,

The feature is much needed, as said in the documentation, it allow a hash tag with multiple words to be concatenated, e.g free software before this feature was translated to #free #software which does not mean anything for Twitter. The feature allows free software to become #freesoftware 
So it is a really needed feature and the reason why I forked rss2twitter in the first place.

**Comment by anarcat** [comment]
sure, it's fine that the feature is there, i just don't see why it's compulsory... it should be easier to disable it!

**Comment by chaica** [comment]
ok I understand now.

I guess the proper way to do it is:
- if the option several_words_hashtags_list is not in the config file or if the option several_words_hashtags_list is empty then bypass the hashtag with multiple words process

**Comment by anarcat** [comment]
sure that's fine too

**Comment by anarcat** [comment]
was just trying to share the quickest fix for me :)

**Comment by chaica** [comment]
Sure, and it's much appreciated :)

**Comment by anarcat** [comment]
should i drop this or rewrite it? #7 depends on it, so before rebasing #7, i'd like to know! thanks.

**Comment by chaica** [comment]
Using /dev/null is a quick hack, so yes, this PR should be rewritten in order to be implement a proper way to manage disabling the hashtag list feature.

**Comment by anarcat** [comment]
okay how's that instead: now it's a commandline option, and disabled by default.

i am thinking, as i said earlier, that the config file could stick with just the twitter credentials... that way documentation about those options is more obvious...

**Comment by anarcat** [comment]
btw, this will conflict with #7, however i do it, which is unfortunate because a bunch of commits have piled up there and it will be difficult to rebase...

**Comment by anarcat** [comment]
ok

**Comment by anarcat** [comment]
@chaica how does that look?

**Comment by chaica** [comment]
The PR -  	add back support for config-file hashtaglist was merged. Thanks for your contribution!

**Pull request merged**
