### PR TITLE
syslog support

### PR DESCRIPTION
**Pull request by anarcat**
this branch adds syslog support and small logging improvements

### CODE REVIEW

**Comment by chaica** [comment]
Hi Anarcat,

I hope you're fine. I'm close to release a new version of feed2tweet and I'm really interested in your PR with the syslog support.

Nevertheless the code has changed a lot (py3k migration mostly, use of [PersistentList](https://pypi.python.org/pypi/persistentlist) to store RSS feed ids, don't forget to git pull) and the PR does not merge any more.

If you're interested in pushing it to feed2tweet and if you have time, could you have a look if this PR is easily upgradable? If you're not, I'll give it a try myself. That would be awesome to get information about feed2tweet through syslog.

Regards,
Carl

**Comment by anarcat** [comment]
I am unlikely to find time to work on this in the near future, feel free
to rebase at will!

**Comment by chaica** [comment]
Ok thanks for your quick reply!

**Comment by chaica** [comment]
closing because nobody available to code it.

**Comment by anarcat** [comment]
by "near future" i meant "few months/weeks" - i would have probably have rebased this if asked...

would this be accepted if i try to rebase it?

**Comment by chaica** [comment]
Yes I will. Don't hesitate to offer it again.

**Pull request closed without merging**
