### PR TITLE
make usage run faster by loading tweepy only when necessary

### PR DESCRIPTION
**Pull request by anarcat**

### CODE REVIEW

**Comment by anarcat** [comment]
before:

```
2.45user 0.26system 0:03.13elapsed 86%CPU (0avgtext+0avgdata 43100maxresident)k
17928inputs+0outputs (18major+12140minor)pagefaults 0swaps
```

after:

```
0.21user 0.03system 0:00.26elapsed 96%CPU (0avgtext+0avgdata 17852maxresident)k
0inputs+0outputs (0major+2874minor)pagefaults 0swaps
```

a big 2 seconds here!

**Comment by anarcat** [comment]
you can clearly see, in the profiler output, that this is happening at import time:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.010    0.010    3.405    3.405 feed2tweet:17(<module>)
        1    0.004    0.004    3.153    3.153 __init__.py:7(<module>)
        1    0.001    0.001    3.093    3.093 api.py:5(<module>)
        1    0.001    0.001    3.090    3.090 binder.py:5(<module>)
        1    0.002    0.002    3.089    3.089 __init__.py:42(<module>)
        1    0.000    0.000    2.951    2.951 __init__.py:57(_attach_namespace)
    70/35    0.008    0.000    2.929    0.084 {__import__}
        1    0.002    0.002    2.897    2.897 pyopenssl.py:47(<module>)
        1    0.003    0.003    2.872    2.872 __init__.py:6(<module>)
        1    0.000    0.000    2.864    2.864 rand.py:5(<module>)
        1    0.001    0.001    2.863    2.863 _util.py:1(<module>)
        1    0.000    0.000    2.860    2.860 binding.py:88(__init__)
        1    0.000    0.000    2.860    2.860 binding.py:91(_ensure_ffi_initialized)
        1    0.001    0.001    2.859    2.859 utils.py:23(build_ffi)
        1    0.000    0.000    2.666    2.666 api.py:90(cdef)
        1    0.000    0.000    2.666    2.666 cparser.py:160(parse)
        1    0.005    0.005    2.666    2.666 cparser.py:171(_internal_parse)
        1    0.000    0.000    2.430    2.430 cparser.py:105(_parse)
        1    0.000    0.000    2.314    2.314 c_parser.py:118(parse)
        1    0.000    0.000    2.314    2.314 yacc.py:261(parse)
        1    0.638    0.638    2.314    2.314 yacc.py:873(parseopt_notrack)
    15098    0.038    0.000    0.530    0.000 c_lexer.py:76(token)
    15098    0.208    0.000    0.493    0.000 lex.py:311(token)
```

it's mostly pyopenssl that's screwing things up...

**Comment by anarcat** [comment]
hmm... but this conflicts with other PRs here, most notably #13 because it needs tweepy in multiple places... not sure how to solve this.

**Comment by chaica** [comment]
usually feed2tweet only runs from time to time. Perfs are not a priority yet. thanks for the PR.

**Pull request closed without merging**
