### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by anarcat**
this PR is built on top of #3, #4 and #5. it aims to cleanup the code by removing code duplication and ambiguities about how the default mode works.

to quote 3e9631a:

> this changes the default behavior to be a little less confusing: instead of tweeting just one RSS entry, it tweets the last RSS entries found, up to the one that was already recorded in the cache file or LIMIT is hit.
> 
> --all behavior isn't changed, although we refactored the code and help docs for the behavior to be a little more clear (that is, we skip the cache file)
>
> incidentally, we inject the docstring in the usage to clarify what this does

also, oldest posts are tweeted first now.

### CODE REVIEW

**Comment by anarcat** [comment]
turns out my idea of posting oldest entries first didn't quite work well, so i reverted that... sorry for the noise.

**Comment by chaica** [comment]
Hi,

Thanks for your PR, I'll read it asap and let you know what I think about it.

Cheers,
Carl

**Comment by anarcat** [comment]
thanks!

**Comment by chaica** [comment]
Could you add ways to not only trigger the debug and the verbose mode from the command line but also from the configuration file? maybe an new section **[logging]** in the configuration files with argument **verbose=yes** and **debug=yes** ?

**Comment by anarcat** [comment]
the logging module supports such things, but i figured it could be done later (as could syslog support, for example). good examples of such code can be found in borg backup and bup-cron, on github.

**Comment by anarcat** [comment]
i rerolled this to resolve the conflict, but i'd rather keep config file support and syslog to separate issues for now, just to keep this from diverging too much.

**Comment by chaica** [comment]
The PR - Refactor was merged. Thanks for your contribution!

**Pull request merged**
