### PR TITLE
move more options out of the config file

### PR DESCRIPTION
**Pull request by anarcat**
with this, all options but twitter secrets are out of the config file.

this is necessary to allow running multiple clients, on multiple feeds, with a shared twitter credentials file.

it is also necessary to make dynamic oauth easier to configure (#9).

this PR builds on top of #7 and #4.

### CODE REVIEW

**Comment by chaica** [comment]
why not letting the user choose what he prefers and offer both ways to have an option, either by a config file either by command line option? It seems the best way to me to please everyone

**Comment by anarcat** [comment]
On 2016-01-02 04:27:12, chaica wrote:
> why not letting the user choose what he prefers and offer both ways to have an option, either by a config file either by command line option? It seems the best way to me to please everyone

my idea is to make the config file just hold the twitter credentials and
be dynamically generated. basically, it's to make the user forget about
it and configure the software strictly through the commandline and the
tags config file.

right now, we have *two* config files - it's a little confusing, no?

-- 
I'm sorry if any of you are catholic. I'm not sorry if you're
offended, I'm actually just sorry by the fact that you're catholic
                         - Bill Hicks

**Comment by chaica** [comment]
As I say before, there are usually 2 schools, people fond of using command line options/arguments and people fond of configuration files. Lets please both schools, that's maximizing the joy of the users :) In my own use of feed2tweet, I use only configuration file launching: 
```
$ feed2tweet feed2tweet.ini
```
one executable, one argument which is the configuration file, pretty easy to understand I guess.

Any serious command line program (ssh, lftp, screen, etc) takes either arguments from the command line or from a configuration or usually both sources.
I'm not sure to understand what you mean by "dynamically generated". IMHO I usually dislike any kind of "dynamically generated" configuration because you often finish with an unexpected state of your configuration.

**Comment by anarcat** [comment]
by "dynamically generated", i mean that people don't have to copy-paste twitter credentials into a config file.

but okay, i'll try to reroll all of this while keeping config file options as default. it will be a major PITA since all those branches are conflicting all over the place now, but meh.

**Comment by anarcat** [comment]
okay - i *think* that restores all config file options

**Comment by chaica** [comment]
I guess there is a bug with the 
```
    parser.add_argument('--cachefile', dest='cachefile',
                        default=os.path.join(os.getenv('XDG_CACHE_HOME', '~/.cache'), 'feed2tweet.dat'),
                        help='location of the cache file (default: %(default)s)')
```
and
```
    if cachefile is None:
        cachefile = config.get('cache', 'cachefile')
```
if your --cache has a default, it means it is never None. So I can't use cachefile from the config file.
Except this point it seems ok to me. Could you fix this issue and I'll push my tests forward ? thanks a lot

**Comment by anarcat** [comment]
right, okay.

**Comment by anarcat** [comment]
do note that #7 should probably be merged before this.

**Comment by anarcat** [comment]
fixed

**Comment by chaica** [comment]
Ok I'm going to merge this one, but next time you need to - really - separate things and test thoroughly each PR :) Don't hesitate to make smaller PRs. I found minor typos in the #4 and in the #7 and that last one is a hugh to review and merge, at least for me :)

**Comment by chaica** [comment]
Ok the current working code lives now in the repository. I'll test all options and config files, make small improvements before releasing. I'd like to create a AUTHORS file, do you want your name, last name and email in it? If so, can I have your email address?

**Comment by anarcat** [comment]
On 2016-01-04 18:43:40, chaica wrote:
> Ok the current working code lives now in the repository. I'll test all options and config files, make small improvements before releasing. I'd like to create a AUTHORS file, do you want your name, last name and email in it? If so, can I have your email address? 

Antoine Beaupré <anarcat@debian.org>

thanks!

ps: sorry, i should have tested all of this, but got a little carried
away by the coding side of it... ;)

**Pull request merged**
